### ISSUE TITLE
confused about the difference between the labels and genes.

### ISSUE THREAD

**Issue by berylsheep-up** [joel-simon/ganbreeder#18]
Hello! This is an excellent job!
When I browse the official artbreed website, I found we can direct edit the genes of an image. If we are going to train the bigGAN,  whether the genes like bangs, black hair are actually the labels?
![image](https://user-images.githubusercontent.com/60908385/75102441-6fa43580-5626-11ea-8f3b-0b0ee832fc91.png)

**Comment by joel-simon** [comment]
Hi there, the live version of Artbreeder uses an additional model called Stylegan not present in this library. In stylegan the genes are learned latent vectors and in biggan the genes are the labels. 

best,
Joel

**Comment by berylsheep-up** [comment]
Hello, I wonder how can i learned the latent vectors like blues eyes? @joel-simon
