### ISSUE TITLE
Unexpected CUDA error: out of memory

### ISSUE THREAD

**Issue by ruanjiyang** [joel-simon/ganbreeder#19]
I run "python server.py" and got the error "Unexpected CUDA error: out of memory".  My GPU is 2080ti with 11GB memory.  Could you let me know how to correct it? thanks!

**Comment by ruanjiyang** [comment]
I had tried in windows 10 and Ubuntu 20.04, both has the same error.

**Comment by joel-simon** [comment]
Hey, this seems like a local issue since it can difficulty run with 11gb. Just in case make sure nothing with "nvidia-smi" running and right cuda_visible_devices set
best,
Joel
