### ISSUE TITLE
View raw vectors for starred images

### ISSUE THREAD

**Issue by nathanbaur** [joel-simon/ganbreeder#6]
Before the latest redesign, it was possible to get the raw z and label vectors for an image. I'd love to have that functionality restored so that I can take images generated by ganbreeder and continue to tweak them with my own code.

**Comment by joel-simon** [comment]
Hi,
That button removed because the UI was getting cluttered and it was only used by a few people. However, it's still there. I may add it back somehow, for now you can manually change the URl from /i?key=<key> to /info?key=<key> to get it.
Sorry about that!

**Comment by nathanbaur** [comment]
Thanks for the quick response! That workaround should be all I need

**Comment by dffinch** [comment]
@joel-simon  What happened to this? It was working previously but now trying this just redirects to the homepage
