### ISSUE TITLE
Utilize parts of your project to mix images (for use in an animation)?

### ISSUE THREAD

**Issue by xrd** [joel-simon/ganbreeder#8]
I've been exploring your project and first off: thanks for making this open source. I've learned a lot.

I'm interested in using parts your project to mix two images. I have an art project in mind where I  take two images with a camera in slightly different positions and then use a GAN to create interval frames and then stitch them together into a video. I'm wondering if I can create something that looks like an animation, but with hopefully slightly strange images from a GAN.

Would your project be suitable for this? And, if so, do you have suggestions on how I could send image data correctly to the server? Ideally I would love to be able to just make a POST request with cURL like:

```
curl -d "@image1.png" -d "@image2.png" -X POST http://localhost:3000/mix_images
```

**Comment by joel-simon** [comment]
Hi, unfortunately, the issue is that you cannot input your own images into the system (or any GAN) right now. However, if you would like to make an animation of images from ganbreeder someone made a tool for that - https://gitlab.com/Vee9ahd1/gantools/tree/master
Best,
Joel
